### ISSUE TITLE
deployment broken

### ISSUE THREAD

**Issue by zuchka** [Nezteb/railway-elixir-phoenix-template#2]
hi,

it looks like this template is broken. I'm getting this error when I deploy:

```
Dockerfile:27

-------------------

25 |     RUN  mix compile

26 |     RUN  mix assets.deploy

27 | >>> RUN  mix ecto.migrate

28 |     RUN  mix run priv/repo/seeds.exs

29 |

-------------------

ERROR: failed to solve: process "/bin/bash -ol pipefail -c mix ecto.migrate" did not complete successfully: exit code: 1

 

Error: Docker build failed
```

**Comment by Nezteb** [comment]
Hi @zuchka! Thanks for letting me know. At the time I was having trouble getting my template to work. It's been a while since I looked at Railway, but your engagement has revitalized my interest. 😄 

Hopefully I'll have some time to look at this over the weekend and let you know what's up!

**Comment by Nezteb** [comment]
@zuchka Actually I just looked into this finally and learned about [the pricing changes](https://www.reddit.com/r/webdev/comments/143tfc2/railway_the_heroku_alternative_shuts_down_their/) that occurred [after I started this repo](https://github.com/Nezteb/railway-elixir-phoenix-template/commits/main/) that has made me lose interest in continuing this, so I'm archiving the repo and probably eventually deleting it. Feel free to fork the template before then!
